-- MockEntity 테이블 생성
CREATE TABLE mock_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mock_entity_name ON mock_entity(name);

-- MockField 테이블 생성
CREATE TABLE mock_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    raw_value VARCHAR(255) NOT NULL,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mock_field_entity FOREIGN KEY (entity_id) REFERENCES mock_entity(id) ON DELETE CASCADE,
    CONSTRAINT uk_mock_field_entity_name UNIQUE (entity_id, name)
);

CREATE INDEX idx_mock_field_entity_id ON mock_field(entity_id);

-- MockEndpoint 테이블 생성
CREATE TABLE mock_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path VARCHAR(500) NOT NULL,
    http_method VARCHAR(20) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mock_endpoint_path_method UNIQUE (path, http_method)
);

CREATE INDEX idx_mock_endpoint_path_method ON mock_endpoint(path, http_method);

-- MockResponse 테이블 생성
CREATE TABLE mock_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_id BIGINT NOT NULL,
    entity_id BIGINT,
    response_data JSONB,
    status_code INTEGER NOT NULL DEFAULT 200,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mock_response_endpoint FOREIGN KEY (endpoint_id) REFERENCES mock_endpoint(id) ON DELETE CASCADE,
    CONSTRAINT fk_mock_response_entity FOREIGN KEY (entity_id) REFERENCES mock_entity(id) ON DELETE SET NULL
);

CREATE INDEX idx_mock_response_endpoint_id ON mock_response(endpoint_id);
CREATE INDEX idx_mock_response_entity_id ON mock_response(entity_id);
